export const VIDEO_FORMATS = [
  {
    id: 'custom',
    label: 'Personalizado Livre',
    max: undefined,
    min: undefined,
    group: 'Outros',
  },
  {
    id: 'yt_shorts',
    label: 'YouTube Shorts',
    max: 60,
    min: undefined,
    group: 'YouTube',
  },
  {
    id: 'yt_long',
    label: 'YouTube Long-form (Mid-roll)',
    max: undefined,
    min: 480,
    group: 'YouTube',
  },
  {
    id: 'tk_15',
    label: 'TikTok (15s)',
    max: 15,
    min: undefined,
    group: 'TikTok',
  },
  {
    id: 'tk_60',
    label: 'TikTok (60s)',
    max: 60,
    min: undefined,
    group: 'TikTok',
  },
  {
    id: 'tk_180',
    label: 'TikTok (3m)',
    max: 180,
    min: undefined,
    group: 'TikTok',
  },
  {
    id: 'ig_15',
    label: 'Instagram Reels (15s)',
    max: 15,
    min: undefined,
    group: 'Instagram',
  },
  {
    id: 'ig_30',
    label: 'Instagram Reels (30s)',
    max: 30,
    min: undefined,
    group: 'Instagram',
  },
  {
    id: 'ig_60',
    label: 'Instagram Reels (60s)',
    max: 60,
    min: undefined,
    group: 'Instagram',
  },
  {
    id: 'ig_90',
    label: 'Instagram Reels (90s)',
    max: 90,
    min: undefined,
    group: 'Instagram',
  },
]
